CREATE DATABASE IF NOT EXISTS lab;
USE lab;

CREATE TABLE IF NOT EXISTS counters (
  id INT PRIMARY KEY,
  value INT NOT NULL
);

INSERT INTO counters (id, value) VALUES (1, 0)
ON DUPLICATE KEY UPDATE value = VALUES(value);

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'lab';
GRANT CONNECTION_ADMIN, PROCESS ON *.* TO 'admin'@'%';

CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'lab' WITH MAX_USER_CONNECTIONS 16;
GRANT SELECT, UPDATE ON lab.* TO 'app'@'%';
